import type { Category, Product } from "@/lib/db/schema";

export const ALL_PRODUCTS_COLLECTION_SLUG = "all-products";
export const PRODUCTS_PER_PAGE = 12;

export const placeholderProducts: Product[] = [
  {
    id: "p1",
    slug: "seoul-1988-serum",
    name: "Seoul 1988 Serum",
    description: "Retinal Liposome 2% + Black Ginseng",
    price: null,
    images: ["/brand/IMG_1549.JPG.jpeg"],
    origin: "KR",
    category: "Serums",
    collectionSlug: "serum",
    inStock: true,
    featured: true,
    isNewArrival: true,
    isBackInStock: false,
    createdAt: new Date("2026-04-10"),
    updatedAt: new Date("2026-04-10"),
  },
  {
    id: "p2",
    slug: "centella-toning-set",
    name: "Centella Toning Set",
    description: "Madagascar Centella Toner + Ampoule · SKIN1004",
    price: null,
    images: ["/brand/IMG_4709.JPG.jpeg"],
    origin: "KR",
    category: "Toner",
    collectionSlug: "toner",
    inStock: true,
    featured: true,
    isNewArrival: false,
    isBackInStock: true,
    createdAt: new Date("2026-03-28"),
    updatedAt: new Date("2026-04-18"),
  },
  {
    id: "p3",
    slug: "dr-althea-relief-cream",
    name: "Dr. Althea Relief Cream",
    description: "345 Relief Cream · Pro Lab · All Skin Types",
    price: null,
    images: ["/brand/IMG_9850.JPG.jpeg"],
    origin: "KR",
    category: "Moisturizer",
    collectionSlug: "moisturiser",
    inStock: true,
    featured: true,
    isNewArrival: true,
    isBackInStock: false,
    createdAt: new Date("2026-04-14"),
    updatedAt: new Date("2026-04-14"),
  },
  {
    id: "p4",
    slug: "eos-body-lotion-set",
    name: "EOS Shea Better Body Lotion",
    description: "24H Moisture · 7 Nourishing Oils + Butters",
    price: null,
    images: ["/brand/IMG_3841.JPG.jpeg"],
    origin: "US",
    category: "Body Care",
    collectionSlug: "body",
    inStock: true,
    featured: false,
    isNewArrival: false,
    isBackInStock: true,
    createdAt: new Date("2026-03-22"),
    updatedAt: new Date("2026-04-17"),
  },
  {
    id: "p5",
    slug: "numbuzin-glow-set",
    name: "Numbuzin 9+ Glow Set",
    description: "High-PDRN Glow Toning Toner + Essence",
    price: null,
    images: ["/brand/IMG_6389.JPG.jpeg"],
    origin: "KR",
    category: "Toner",
    collectionSlug: "toner",
    inStock: true,
    featured: false,
    isNewArrival: true,
    isBackInStock: false,
    createdAt: new Date("2026-04-16"),
    updatedAt: new Date("2026-04-16"),
  },
];

export const placeholderCollections: Category[] = [
  {
    id: "c1",
    name: "Serum",
    slug: "serum",
    description: "Targeted formulas for glow, texture and treatment support.",
    image: "/brand/IMG_1549.JPG.jpeg",
    sortOrder: 1,
  },
  {
    id: "c2",
    name: "Toner",
    slug: "toner",
    description: "Prep, hydrate and rebalance your routine with toning essentials.",
    image: "/brand/IMG_4709.JPG.jpeg",
    sortOrder: 2,
  },
  {
    id: "c3",
    name: "Moisturiser",
    slug: "moisturiser",
    description: "Barrier-supporting creams and gels for everyday skin comfort.",
    image: "/brand/IMG_9850.JPG.jpeg",
    sortOrder: 3,
  },
  {
    id: "c4",
    name: "Body",
    slug: "body",
    description: "Body care picks that keep skin soft, smooth and nourished.",
    image: "/brand/IMG_3841.JPG.jpeg",
    sortOrder: 4,
  },
];
